from __future__ import annotations

import json

import pytest

from pipeline_codegen.errors import GenerationError
from pipeline_codegen.llm import client


class _FakeResponse:
    def __init__(self, payload: dict) -> None:
        self._payload = payload

    def __enter__(self) -> "_FakeResponse":
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        return False

    def read(self) -> bytes:
        return json.dumps(self._payload).encode("utf-8")


def test_complete_chat_supports_all_configured_providers(monkeypatch) -> None:
    def _fake_urlopen(req, timeout=60):  # type: ignore[no-untyped-def]
        url = req.full_url
        if "anthropic.com" in url:
            return _FakeResponse({"content": [{"type": "text", "text": "print('claude')"}]})
        if "11434" in url:
            return _FakeResponse({"message": {"content": "print('ollama')"}})
        return _FakeResponse({"choices": [{"message": {"content": "print('compatible')"}}]})

    monkeypatch.setattr(client.request, "urlopen", _fake_urlopen)

    compatible = ["openai", "openrouter", "deepinfra", "deepseek"]
    for provider in compatible:
        out = client.complete_chat(
            system_prompt="sys",
            user_prompt="user",
            llm_config={"provider": provider, "api_key": "k"},
        )
        assert out == "print('compatible')"

    assert (
        client.complete_chat(
            system_prompt="sys",
            user_prompt="user",
            llm_config={"provider": "claude", "api_key": "k"},
        )
        == "print('claude')"
    )
    assert (
        client.complete_chat(
            system_prompt="sys",
            user_prompt="user",
            llm_config={"provider": "ollama"},
        )
        == "print('ollama')"
    )


def test_generate_python_task_body_supports_stub_and_strips_code_fences(monkeypatch) -> None:
    stub = client.generate_python_task_body({"id": "task_1"}, llm_config={"provider": "stub"})
    assert "# generated by llm-assisted (stub)" in stub
    assert "print('task task_1')" in stub

    monkeypatch.setattr(client, "complete_chat", lambda **kwargs: "```python\nprint('x')\n```")
    code = client.generate_python_task_body({"id": "task_2"}, llm_config={"provider": "openai", "api_key": "k"})
    assert code == "print('x')"


def test_complete_chat_rejects_unsupported_provider() -> None:
    with pytest.raises(GenerationError) as exc:
        client.complete_chat("sys", "user", {"provider": "unknown"})
    assert "unsupported llm provider" in str(exc.value)
