from airflow import DAG
from datetime import datetime
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator

with DAG(dag_id="dagster_fanout_quality", start_date=datetime(2024,1,1), schedule=None, catchup=False) as dag:
    def _fn_extract_source():
        # generated by llm-assisted (stub)
        print('task extract_source')
    extract_source = PythonOperator(task_id="extract_source", python_callable=_fn_extract_source)
    def _fn_enrich_region_a():
        # generated by llm-assisted (stub)
        print('task enrich_region_a')
    enrich_region_a = PythonOperator(task_id="enrich_region_a", python_callable=_fn_enrich_region_a)
    def _fn_enrich_region_b():
        # generated by llm-assisted (stub)
        print('task enrich_region_b')
    enrich_region_b = PythonOperator(task_id="enrich_region_b", python_callable=_fn_enrich_region_b)
    quality_gate = BashOperator(task_id="quality_gate", bash_command="echo quality_gate")
    def _fn_publish_curated():
        # generated by llm-assisted (stub)
        print('task publish_curated')
    publish_curated = PythonOperator(task_id="publish_curated", python_callable=_fn_publish_curated)

    enrich_region_a >> quality_gate
    enrich_region_b >> quality_gate
    extract_source >> enrich_region_a
    extract_source >> enrich_region_b
    quality_gate >> publish_curated
