from airflow import DAG
from datetime import datetime
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator

with DAG(dag_id="prefect_ml_lifecycle", start_date=datetime(2024,1,1), schedule=None, catchup=False) as dag:
    def _fn_prepare_features():
        # generated by llm-assisted (stub)
        print('task prepare_features')
    prepare_features = PythonOperator(task_id="prepare_features", python_callable=_fn_prepare_features)
    def _fn_train_model():
        # generated by llm-assisted (stub)
        print('task train_model')
    train_model = PythonOperator(task_id="train_model", python_callable=_fn_train_model)
    def _fn_evaluate_model():
        # generated by llm-assisted (stub)
        print('task evaluate_model')
    evaluate_model = PythonOperator(task_id="evaluate_model", python_callable=_fn_evaluate_model)
    def _fn_notify_release():
        # generated by llm-assisted (stub)
        print('task notify_release')
    notify_release = PythonOperator(task_id="notify_release", python_callable=_fn_notify_release)

    evaluate_model >> notify_release
    prepare_features >> train_model
    train_model >> evaluate_model
